export const REPORT_REQUEST_TIMEOUT_MS = 90_000;
export const AUTH_ME_REQUEST_TIMEOUT_MS = 3_000;
export const AUTH_GUEST_REQUEST_TIMEOUT_MS = 3_000;
export const AUTH_GOOGLE_REQUEST_TIMEOUT_MS = 25_000;
export const HEALTH_REQUEST_TIMEOUT_MS = 25_000;
export const START_SESSION_TIMEOUT_MS = 90_000;
export const SUBMIT_ANSWER_TIMEOUT_MS = 180_000;
export const SESSION_READ_TIMEOUT_MS = 30_000;
